"use client"

import { useState, useCallback } from "react"
import { Sidebar } from "@/components/tender-intelligence/sidebar"
import { AgentChat, Message, AgentStep } from "@/components/tender-intelligence/agent-chat"
import { ContextPanel, TenderData, ApprovalItem } from "@/components/tender-intelligence/context-panel"
import { InsightsPanel } from "@/components/tender-intelligence/insights-panel"
import { AboutPage } from "@/components/tender-intelligence/about-page"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

// Mock tender data matching OCDS standard
const mockTenderData: TenderData = {
  ocid: "AU-AUSTENDER-2024-CN4892761",
  tender: {
    id: "CN4892761",
    title: "Cybersecurity Assessment and Penetration Testing Services",
    description: "Provision of comprehensive cybersecurity assessment, vulnerability scanning, and penetration testing services for critical government infrastructure across New South Wales state agencies.",
    status: "active",
    value: {
      amount: 2450000,
      currency: "AUD"
    },
    procuringEntity: {
      name: "NSW Department of Customer Service",
      id: "AU-ABN-75847878271"
    },
    tenderPeriod: {
      startDate: "2024-11-15T00:00:00Z",
      endDate: "2025-01-31T17:00:00Z"
    },
    mainProcurementCategory: "services",
    additionalProcurementCategories: ["ICT", "Security", "Consulting"],
    awardCriteria: "bestValueToGovernment",
    submissionMethod: ["electronicSubmission"]
  },
  buyer: {
    name: "NSW Government Procurement",
    id: "AU-ABN-75847878271",
    address: {
      region: "New South Wales",
      countryName: "Australia"
    }
  }
}

const mockApprovalItem: ApprovalItem = {
  id: "apr_8f2k9d3m1n5v",
  type: "email",
  title: "Tender Summary Email Draft",
  description: "Auto-generated email summarizing cybersecurity tenders matching your criteria for stakeholder distribution.",
  content: `Subject: Weekly Procurement Alert - Cybersecurity Opportunities NSW

Dear Procurement Team,

This week's analysis identified 3 high-value cybersecurity opportunities in NSW:

1. Cybersecurity Assessment Services - $2.45M (Closes: Jan 31)
   Entity: NSW Department of Customer Service
   
2. SOC Operations Managed Services - $4.2M (Closes: Feb 15)
   Entity: NSW Treasury
   
3. Identity & Access Management - $1.8M (Closes: Feb 28)
   Entity: Service NSW

Recommended Action: Prioritize opportunity #1 based on capability alignment and timeline.

Generated by Tender Intelligence | Requires HITL Approval`,
  riskLevel: "low",
  createdAt: new Date(),
  relatedTender: "AU-AUSTENDER-2024-CN4892761"
}

export default function TenderIntelligencePage() {
  const [activeNavItem, setActiveNavItem] = useState("new-query")
  const [messages, setMessages] = useState<Message[]>([])
  const [isLoading, setIsLoading] = useState(false)
  const [tenderData, setTenderData] = useState<TenderData | null>(null)
  const [allTenders, setAllTenders] = useState<any[]>([])
  const [approvalItem, setApprovalItem] = useState<ApprovalItem | null>(mockApprovalItem)

  const simulateAgentResponse = useCallback(async (userQuery: string) => {
    setIsLoading(true)
    
    const userMessage: Message = {
      id: `msg_${Date.now()}`,
      role: "user",
      content: userQuery,
      timestamp: new Date()
    }
    setMessages(prev => [...prev, userMessage])

    const tempMessageId = `msg_${Date.now() + 1}`;
    setMessages(prev => [...prev, {
      id: tempMessageId,
      role: "assistant",
      content: "Connecting to AusTender MCP...",
      timestamp: new Date(),
      steps: [{ id: "1", status: "running", label: "Establishing MCP connection" }]
    }]);

    try {
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: userQuery })
      });

      const data = await response.json();

      setMessages(prev => prev.map(msg => 
        msg.id === tempMessageId 
          ? {
              id: tempMessageId,
              role: "assistant",
              content: data.content,
              timestamp: new Date(),
              steps: data.steps
            }
          : msg
      ));

      if (data.allTenders && data.allTenders.length > 0) {
        setAllTenders(data.allTenders);
        const topData = data.allTenders[0];
        setTenderData({
          ocid: `AU-AUSTENDER-${topData.CNID || "UNKNOWN"}`,
          tender: {
            id: topData.CNID || "UNKNOWN",
            title: topData.Title,
            description: topData.description || "Data retrieved securely via Model Context Protocol.",
            status: "active",
            value: { amount: parseFloat(topData.Value?.replace(/[^0-9.-]+/g, '')) || 0, currency: "AUD" },
            procuringEntity: { name: topData.Agency, id: "AU-GOV-AGENCY" },
            tenderPeriod: { startDate: topData.PublishedDate, endDate: topData.PublishedDate },
            mainProcurementCategory: topData.Category,
            additionalProcurementCategories: [],
            awardCriteria: "bestValueToGovernment",
            submissionMethod: ["electronicSubmission"]
          },
          buyer: {
            name: topData.Agency,
            id: "AU-GOV-AGENCY",
            address: { region: "Australia", countryName: "Australia" }
          }
        });
      } else if (data.rawData && data.rawData.CNID) {
        // Fallback in case rawData is the tender object itself
        const topData = data.rawData;
        setTenderData({
          ocid: `AU-AUSTENDER-${topData.CNID || "UNKNOWN"}`,
          tender: {
            id: topData.CNID || "UNKNOWN",
            title: topData.Title,
            description: topData.description || "Data retrieved securely via Model Context Protocol.",
            status: "active",
            value: { amount: parseFloat(topData.Value?.replace(/[^0-9.-]+/g, '')) || 0, currency: "AUD" },
            procuringEntity: { name: topData.Agency, id: "AU-GOV-AGENCY" },
            tenderPeriod: { startDate: topData.PublishedDate, endDate: topData.PublishedDate },
            mainProcurementCategory: topData.Category,
            additionalProcurementCategories: [],
            awardCriteria: "bestValueToGovernment",
            submissionMethod: ["electronicSubmission"]
          },
          buyer: {
            name: topData.Agency,
            id: "AU-GOV-AGENCY",
            address: { region: "Australia", countryName: "Australia" }
          }
        });
      }

    } catch (error) {
      console.error(error);
      setMessages(prev => prev.map(msg => 
        msg.id === tempMessageId 
          ? { ...msg, content: "Error connecting to MCP server.", steps: [{ id: "err", status: "error", label: "Connection Failed" }] }
          : msg
      ));
    } finally {
      setIsLoading(false)
    }
  }, [])

  const handleApprove = (id: string) => {
    setApprovalItem(null)
    // Add confirmation message
    const confirmMessage: Message = {
      id: `msg_${Date.now()}`,
      role: "assistant",
      content: "✓ **Email approved and sent** to the procurement team distribution list. Action logged under audit ID HITL-" + id.slice(0, 8).toUpperCase() + ".",
      timestamp: new Date()
    }
    setMessages(prev => [...prev, confirmMessage])
  }

  const handleReject = (id: string) => {
    setApprovalItem(null)
    const rejectMessage: Message = {
      id: `msg_${Date.now()}`,
      role: "assistant",
      content: "Email draft rejected. Would you like me to revise the content or generate a different format?",
      timestamp: new Date()
    }
    setMessages(prev => [...prev, rejectMessage])
  }

  return (
    <div className="flex h-screen w-screen bg-slate-50 dark:bg-slate-950 overflow-hidden">
      {/* Left Sidebar */}
      <div className="hidden md:block h-full shrink-0">
        <Sidebar
          activeItem={activeNavItem}
          onItemClick={setActiveNavItem}
          pendingApprovals={approvalItem ? 1 : 0}
        />
      </div>

      {/* Main Content Area */}
      <div className="flex flex-1 min-w-0 min-h-0">
        {/* Center - Content */}
        <div className="flex-1 min-w-0 min-h-0 h-full overflow-hidden">
          {activeNavItem === "about" ? (
            <AboutPage />
          ) : (
            <AgentChat
              messages={messages}
              isLoading={isLoading}
              onSendMessage={simulateAgentResponse}
            />
          )}
        </div>

        {/* Right - Context Panel with Tabs */}
        <div className="hidden lg:block w-[480px] shrink-0 border-l border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 h-full overflow-hidden">
          <Tabs defaultValue="context" className="w-full">
            <TabsList className="w-full grid grid-cols-2 rounded-none border-b">
              <TabsTrigger value="context">Context</TabsTrigger>
              <TabsTrigger value="insights">AI Insights</TabsTrigger>
            </TabsList>
            
            <TabsContent value="context" className="m-0 p-4">
              <ContextPanel
                tenderData={tenderData}
                allTenders={allTenders}
                approvalItem={approvalItem}
                onApprove={handleApprove}
                onReject={handleReject}
              />
            </TabsContent>
            
            <TabsContent value="insights" className="m-0 p-4">
              <InsightsPanel 
                tender={tenderData ? {
                  CNID: tenderData.tender.id,
                  Title: tenderData.tender.title,
                  Agency: tenderData.tender.procuringEntity.name,
                  Category: tenderData.tender.mainProcurementCategory,
                  PublishedDate: tenderData.tender.tenderPeriod.startDate,
                  Value: `$${tenderData.tender.value.amount.toLocaleString()} ${tenderData.tender.value.currency}`,
                  description: tenderData.tender.description
                } : null}
              />
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </div>
  )
}
