"use client"

import { useState, useCallback, useEffect } from "react"
import { Sidebar } from "@/components/tender-intelligence/sidebar"
import { AgentChat, Message, AgentStep } from "@/components/tender-intelligence/agent-chat"
import { ContextPanel, TenderData, ApprovalItem } from "@/components/tender-intelligence/context-panel"
import { InsightsPanel } from "@/components/tender-intelligence/insights-panel"
import { AboutPage } from "@/components/tender-intelligence/about-page"
import { MobileNav } from "@/components/tender-intelligence/mobile-nav"
import { DesktopBanner } from "@/components/tender-intelligence/desktop-banner"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Button } from "@/components/ui/button"
import { PanelRightOpen, PanelRightClose, Sparkles } from "lucide-react"
import Link from "next/link"

// Mock tender data matching OCDS standard
const mockTenderData: TenderData = {
  ocid: "AU-AUSTENDER-2024-CN4892761",
  tender: {
    id: "CN4892761",
    title: "Cybersecurity Assessment and Penetration Testing Services",
    description: "Provision of comprehensive cybersecurity assessment, vulnerability scanning, and penetration testing services for critical government infrastructure across New South Wales state agencies.",
    status: "active",
    value: { amount: 2450000, currency: "AUD" },
    procuringEntity: { name: "NSW Department of Customer Service", id: "AU-ABN-75847878271" },
    tenderPeriod: { startDate: "2024-11-15T00:00:00Z", endDate: "2025-01-31T17:00:00Z" },
    mainProcurementCategory: "services",
    additionalProcurementCategories: ["ICT", "Security", "Consulting"],
    awardCriteria: "bestValueToGovernment",
    submissionMethod: ["electronicSubmission"]
  },
  buyer: {
    name: "NSW Government Procurement",
    id: "AU-ABN-75847878271",
    address: { region: "New South Wales", countryName: "Australia" }
  }
}

const mockApprovalItem: ApprovalItem = {
  id: "apr_8f2k9d3m1n5v",
  type: "email",
  title: "Tender Summary Email Draft",
  description: "Auto-generated email summarizing cybersecurity tenders matching your criteria for stakeholder distribution.",
  content: `Subject: Weekly Procurement Alert - Cybersecurity Opportunities NSW\n\nDear Procurement Team,\n\nThis week's analysis identified 3 high-value opportunities:\n\n1. Cybersecurity Assessment Services - $2.45M (Closes: Jan 31)\n   Entity: NSW Department of Customer Service\n\n2. SOC Operations Managed Services - $4.2M (Closes: Feb 15)\n   Entity: NSW Treasury\n\n3. Identity & Access Management - $1.8M (Closes: Feb 28)\n   Entity: Service NSW\n\nRecommended Action: Prioritize #1 based on alignment and timeline.\n\nGenerated by Tender Intelligence | Requires HITL Approval`,
  riskLevel: "low",
  createdAt: new Date(),
  relatedTender: "AU-AUSTENDER-2024-CN4892761"
}

export default function TenderDiscoveryPage() {
  const [activeNavItem, setActiveNavItem] = useState("new-query")
  const [messages, setMessages] = useState<Message[]>([])
  const [isLoading, setIsLoading] = useState(false)
  const [tenderData, setTenderData] = useState<TenderData | null>(null)
  const [allTenders, setAllTenders] = useState<any[]>([])
  const [approvalItem, setApprovalItem] = useState<ApprovalItem | null>(mockApprovalItem)
  const [rightPanelOpen, setRightPanelOpen] = useState(false)
  const [isPremium, setIsPremium] = useState(false)
  const [queryCount, setQueryCount] = useState(0)
  const [showPremiumBanner, setShowPremiumBanner] = useState(true)

  // Check premium status on mount
  useEffect(() => {
    fetch('/api/premium/check')
      .then(res => res.json())
      .then(data => {
        setIsPremium(data.premium)
      })
      .catch(() => {})
  }, [])

  const simulateAgentResponse = useCallback(async (userQuery: string) => {
    // Rate limit free users at 5 queries
    if (!isPremium && queryCount >= 5) {
      return
    }

    setIsLoading(true)
    setQueryCount(prev => prev + 1)
    const timestamp = Date.now()
    const userMessage: Message = { id: `msg_user_${timestamp}`, role: "user", content: userQuery, timestamp: new Date() }
    setMessages(prev => [...prev, userMessage])

    const tempMessageId = `msg_assistant_${timestamp}_${Math.random().toString(36).substr(2, 9)}`
    setMessages(prev => [...prev, { id: tempMessageId, role: "assistant", content: "Connecting to AusTender MCP...", timestamp: new Date(), steps: [{ id: "1", status: "running", label: "Establishing MCP connection" }] }])

    try {
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-cache, no-store, must-revalidate' },
        body: JSON.stringify({ message: userQuery })
      })
      const data = await response.json()

      setMessages(prev => prev.map(msg =>
        msg.id === tempMessageId ? { id: tempMessageId, role: "assistant", content: data.content, timestamp: new Date(), steps: data.steps } : msg
      ))

      if (data.allTenders && data.allTenders.length > 0) {
        setAllTenders(data.allTenders)
        const top = data.allTenders[0]
        setTenderData({
          ocid: `AU-AUSTENDER-${top.CNID || "UNKNOWN"}`,
          tender: {
            id: top.CNID || "UNKNOWN",
            title: top.Title,
            description: top.description || "Data retrieved securely via Model Context Protocol.",
            status: "active",
            value: { amount: parseFloat(top.Value?.replace(/[^0-9.-]+/g, '')) || 0, currency: "AUD" },
            procuringEntity: { name: top.Agency, id: "AU-GOV-AGENCY" },
            tenderPeriod: { startDate: top.PublishedDate, endDate: top.PublishedDate },
            mainProcurementCategory: top.Category,
            additionalProcurementCategories: [],
            awardCriteria: "bestValueToGovernment",
            submissionMethod: ["electronicSubmission"]
          },
          buyer: { name: top.Agency, id: "AU-GOV-AGENCY", address: { region: "Australia", countryName: "Australia" } }
        })
      }
    } catch (error) {
      console.error(error)
      setMessages(prev => prev.map(msg =>
        msg.id === tempMessageId ? { ...msg, content: "Error connecting to MCP server.", steps: [{ id: "err", status: "error", label: "Connection Failed" }] } : msg
      ))
    } finally {
      setIsLoading(false)
    }
  }, [isPremium, queryCount])

  const handleApprove = (id: string) => {
    setApprovalItem(null)
    setMessages(prev => [...prev, { id: `msg_${Date.now()}`, role: "assistant", content: "✓ **Email approved and sent** to the procurement team distribution list. Action logged under audit ID HITL-" + id.slice(0, 8).toUpperCase() + ".", timestamp: new Date() }])
  }

  const handleReject = (id: string) => {
    setApprovalItem(null)
    setMessages(prev => [...prev, { id: `msg_${Date.now()}`, role: "assistant", content: "Email draft rejected. Would you like me to revise the content or generate a different format?", timestamp: new Date() }])
  }

  const remainingQueries = 5 - queryCount

  return (
    <>
      <DesktopBanner />
      <div className="flex h-screen w-screen bg-slate-50 dark:bg-slate-950 overflow-hidden pt-0 lg:pt-0">
        <div className="hidden md:block h-full shrink-0">
          <Sidebar activeItem={activeNavItem} onItemClick={setActiveNavItem} pendingApprovals={approvalItem ? 1 : 0} />
        </div>

        <div className="flex flex-1 min-w-0 min-h-0 relative pb-16 lg:pb-0">
          <div className="flex-1 min-w-0 min-h-0 h-full overflow-auto">
            {activeNavItem === "about" ? (
              <AboutPage />
            ) : (
              <>
                {/* Premium upsell banner */}
                {!isPremium && showPremiumBanner && queryCount >= 3 && (
                  <div className="mx-4 mt-4 bg-gradient-to-r from-blue-600 to-indigo-700 rounded-xl p-4 text-white shadow-lg">
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <div className="flex items-center gap-2 mb-1">
                          <Sparkles className="w-4 h-4" />
                          <span className="font-semibold text-sm">Upgrade to Premium</span>
                        </div>
                        <p className="text-sm text-blue-100 mb-3">
                          {queryCount >= 5
                            ? "You've used all 5 free searches. Upgrade for unlimited access."
                            : `${remainingQueries} free searches remaining. Upgrade for unlimited access + email alerts.`}
                        </p>
                        <Link
                          href="/premium"
                          className="inline-flex items-center gap-1.5 bg-white text-blue-700 text-sm font-semibold px-4 py-2 rounded-lg hover:bg-blue-50 transition"
                        >
                          <Sparkles className="w-3.5 h-3.5" />
                          Upgrade - $19/mo
                        </Link>
                      </div>
                      <button
                        onClick={() => setShowPremiumBanner(false)}
                        className="text-white/60 hover:text-white text-sm"
                      >
                        ✕
                      </button>
                    </div>
                  </div>
                )}

                {/* Premium status indicator */}
                {isPremium && (
                  <div className="mx-4 mt-4 flex items-center gap-2 text-xs text-green-600 dark:text-green-400">
                    <Sparkles className="w-3.5 h-3.5" />
                    <span className="font-medium">Premium</span>
                  </div>
                )}

                <AgentChat messages={messages} isLoading={isLoading} onSendMessage={simulateAgentResponse} />
              </>
            )}
          </div>

          <Button size="sm" onClick={() => setRightPanelOpen(!rightPanelOpen)}
            className="absolute right-4 bottom-20 lg:bottom-4 z-50 bg-blue-600/90 hover:bg-blue-700/90 text-white backdrop-blur-md border border-blue-400/30 shadow-lg">
            {rightPanelOpen ? <PanelRightClose className="w-4 h-4" /> : <PanelRightOpen className="w-4 h-4" />}
            <span className="ml-2 font-medium">{rightPanelOpen ? 'Hide' : 'Details'}</span>
          </Button>

          <div className={`${rightPanelOpen ? 'translate-x-0' : 'translate-x-full lg:translate-x-0 lg:hidden'} fixed lg:static right-0 top-0 h-full w-full sm:w-[400px] lg:w-[480px] shrink-0 border-l border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 z-40 transition-transform duration-300 ease-in-out overflow-hidden shadow-2xl lg:shadow-none`}>
            <div className="lg:hidden flex items-center justify-between p-4 border-b">
              <span className="font-semibold">Tender Details</span>
              <Button variant="ghost" size="sm" onClick={() => setRightPanelOpen(false)}>
                <PanelRightClose className="w-4 h-4" />
              </Button>
            </div>
            <Tabs defaultValue="insights" className="w-full h-full flex flex-col">
              <TabsList className="w-full grid grid-cols-2 rounded-none border-b shrink-0">
                <TabsTrigger value="insights">AI Insights</TabsTrigger>
                <TabsTrigger value="context">Details</TabsTrigger>
              </TabsList>
              <TabsContent value="insights" className="m-0 flex-1 overflow-hidden">
                <div className="h-full overflow-y-auto p-4">
                  <InsightsPanel tender={tenderData ? { CNID: tenderData.tender.id, Title: tenderData.tender.title, Agency: tenderData.tender.procuringEntity.name, Category: tenderData.tender.mainProcurementCategory, PublishedDate: tenderData.tender.tenderPeriod.startDate, Value: `$${tenderData.tender.value.amount.toLocaleString()} ${tenderData.tender.value.currency}`, description: tenderData.tender.description } : null} />
                </div>
              </TabsContent>
              <TabsContent value="context" className="m-0 flex-1 overflow-hidden">
                <div className="h-full overflow-y-auto">
                  <ContextPanel tenderData={tenderData} allTenders={allTenders} approvalItem={approvalItem} onApprove={handleApprove} onReject={handleReject} />
                </div>
              </TabsContent>
            </Tabs>
          </div>

          {rightPanelOpen && (
            <div className="lg:hidden fixed inset-0 bg-black/50 z-30" onClick={() => setRightPanelOpen(false)} />
          )}
        </div>

        <MobileNav activeItem={activeNavItem} onItemClick={setActiveNavItem} />
      </div>
    </>
  )
}
